DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS users;

CREATE TABLE admin (
	aid VARCHAR(30) NOT NULL UNIQUE PRIMARY KEY,
	aemail VARCHAR(100) NOT NULL UNIQUE,
	apwd VARCHAR(255) NOT NULL,
	role VARCHAR(20) NOT NULL,
	created_by VARCHAR(30) UNIQUE
);

CREATE TABLE users (
    uid VARCHAR(30) PRIMARY KEY,
    uname VARCHAR(50) NOT NULL,
    uemail VARCHAR(100) NOT NULL UNIQUE,
    upwd VARCHAR(255) NOT NULL,
    uphone VARCHAR(20)
);