DROP TABLE IF EXISTS admin;

CREATE TABLE admin (
	aid VARCHAR(30) NOT NULL UNIQUE PRIMARY KEY,
	aemail VARCHAR(100) NOT NULL UNIQUE,
	apwd VARCHAR(255) NOT NULL,
	role VARCHAR(20) NOT NULL,
	created_by VARCHAR(30) UNIQUE
)