name: Backend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Append OAuth keys to application.properties
        run: |
          echo "" >> src/main/resources/application.properties
          echo "# === OAuth Secrets from GitHub Actions ===" >> src/main/resources/application.properties
          echo "google.client.id=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> src/main/resources/application.properties
          echo "google.client.secret=${{ secrets.VITE_GOOGLE_CLIENT_SECRET }}" >> src/main/resources/application.properties
          echo "google.redirect.uri=${{ secrets.VITE_GOOGLE_REDIRECT_URI }}" >> src/main/resources/application.properties
          echo "google.logout.redirect.uri=${{ secrets.VITE_GOOGLE_LOGOUT_REDIRECT_URI }}" >> src/main/resources/application.properties
          echo "kakao.client.id=${{ secrets.KAKAO_CLIENT_ID }}" >> src/main/resources/application.properties
          echo "kakao.redirect.uri=${{ secrets.KAKAO_REDIRECT_URI }}" >> src/main/resources/application.properties
          echo "kakao.logout.redirect.uri=${{ secrets.VITE_KAKAO_LOGOUT_REDIRECT_URI }}" >> src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.YEDOC }}
          HOST: ${{ secrets.BACKEND_HOST }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          JAR_FILE=$(ls build/libs/*SNAPSHOT.jar | grep -v plain | head -n 1)
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@$HOST "rm -f /home/ec2-user/app.jar"
          scp -i key.pem -o StrictHostKeyChecking=no "$JAR_FILE" ec2-user@$HOST:/home/ec2-user/app.jar

          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@$HOST << 'EOF'
            pkill -f 'java -jar' || true
            echo "Running JAR..."
            nohup /opt/corretto/amazon-corretto-21.0.7.6.1-linux-x64/bin/java -jar /home/ec2-user/app.jar > log.txt 2>&1 &
            sleep 3
            tail -n 20 /home/ec2-user/log.txt
          EOF
